---
title: "R Notebook"
output: html_notebook
---
## Aufgaben zu Session 5
```{r}
library(tidyverse)
library(caret)
library(cluster)
```
```{r}
library(readr)
users <- read_delim("BX-Users.csv", ";", 
    escape_double = FALSE, trim_ws = TRUE)
```
```{r}
library(readr)
ratings <- read_delim("BX-Book-Ratings.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
```
```{r}
library(readr)
books <- read_delim("BX-Books.csv", ";", 
    escape_double = FALSE, trim_ws = TRUE)
```

```{r}
books$`Year-Of-Publication`[books$`Year-Of-Publication` == 0] <-NA
```

```{r}
books1 <- books %>%
  select(ISBN, `Year-Of-Publication`, `Book-Author`, `Book-Title`, Publisher) %>%
  mutate(`Book-Author` = str_to_lower(`Book-Author`), 
         `Book-Author` = str_replace_all(`Book-Author`, "ç", "c"),
         `Book-Author` = str_replace_all(`Book-Author`, "ñ", "n"),
         `Book-Author` = str_replace_all(`Book-Author`, "é", "e"),
         `Book-Author` = str_replace_all(`Book-Author`, "í", "i"),
         `Book-Author` = str_replace_all(`Book-Author`, "ó", "o"),
         `Book-Author` = str_replace_all(`Book-Author`, "ò", "o"),
         `Book-Author` = str_replace_all(`Book-Author`, "ô", "o"),
         `Book-Author` = str_replace_all(`Book-Author`, "ö", "oe"),
         `Book-Author` = str_replace_all(`Book-Author`, "ï", "i"),
         `Book-Author` = str_replace_all(`Book-Author`, "á", "a"),
         `Book-Author` = str_replace_all(`Book-Author`, "à", "a"),
         `Book-Author` = str_replace_all(`Book-Author`, "è", "e"),
         `Book-Author` = str_replace_all(`Book-Author`, "ê", "e"),
         `Book-Author` = str_replace_all(`Book-Author`, "ë", "e"),
         `Book-Author` = str_replace_all(`Book-Author`, "å", "a"),
         `Book-Author` = str_replace_all(`Book-Author`, "ä", "ae"),
         `Book-Author` = str_replace_all(`Book-Author`, "ã", "a"),
         `Book-Author` = str_replace_all(`Book-Author`, "â", "a"),
         `Book-Author` = str_replace_all(`Book-Author`, "ú", "u"),
         `Book-Author` = str_replace_all(`Book-Author`, "ü", "u"),
         `Book-Title` = str_to_lower(`Book-Title`),
         `Book-Title` = str_replace_all(`Book-Title`, "ç", "c"),
         `Book-Title` = str_replace_all(`Book-Title`, "ñ", "n"),
         `Book-Title` = str_replace_all(`Book-Title`, "é", "e"),
         `Book-Title` = str_replace_all(`Book-Title`, "í", "i"),
         `Book-Title` = str_replace_all(`Book-Title`, "ó", "o"),
         `Book-Title` = str_replace_all(`Book-Title`, "ò", "o"),
         `Book-Title` = str_replace_all(`Book-Title`, "ô", "o"),
         `Book-Title` = str_replace_all(`Book-Title`, "ö", "oe"),
         `Book-Title` = str_replace_all(`Book-Title`, "ï", "i"),
         `Book-Title` = str_replace_all(`Book-Title`, "á", "a"),
         `Book-Title` = str_replace_all(`Book-Title`, "à", "a"),
         `Book-Title` = str_replace_all(`Book-Title`, "è", "e"),
         `Book-Title` = str_replace_all(`Book-Title`, "ê", "e"),
         `Book-Title` = str_replace_all(`Book-Title`, "ë", "e"),
         `Book-Title` = str_replace_all(`Book-Title`, "å", "a"),
         `Book-Title` = str_replace_all(`Book-Title`, "ä", "ae"),
         `Book-Title` = str_replace_all(`Book-Title`, "ã", "a"),
         `Book-Title` = str_replace_all(`Book-Title`, "â", "a"),
         `Book-Title` = str_replace_all(`Book-Title`, "ú", "u"),
         `Book-Title` = str_replace_all(`Book-Title`, "ü", "u"),
         `Book-Author` = str_replace_all(`Book-Author`, " .* ", " "),
         Publisher = str_to_lower(Publisher),
         ISBN = str_extract(ISBN, "[0-9]*X*")) 
```


```{r}
ratings$`Book-Rating`[ratings$`Book-Rating` ==  0] <- NA
```



```{r}
users <- users %>%
  mutate(Location = str_remove_all(Location, ".*,"),
         Age = as.numeric(Age))
```
```{r}
users$Location[users$Location == ""] <- NA
```

```{r}
books_w_ratings <- books1 %>%
  left_join(ratings)
```

```{r}
all <- books_w_ratings %>%
  left_join(users)
```


```{r}
all <- na.omit(all)
```



```{r}
all2 <- all[c(1:300),] %>%
  select(`Book-Title`, `User-ID`, `Book-Rating`, Age) 
```

```{r}
all2$beloved <- ifelse(all2$`Book-Title` == "beloved (plume contemporary fiction)", 1, 0)  
all2$clara <- ifelse(all2$`Book-Title` == "clara callan", 1, 0) 
all2$decision_in_normandy <- ifelse(all2$`Book-Title` == "decision in normandy", 1, 0) 
all2$flu <- ifelse(all2$`Book-Title` == "flu: the story of the great influenza pandemic of 1918 and the search for the virus that caused it", 1, 0) 
all2$vegetarian <- ifelse(all2$`Book-Title` == "new vegetarian: bold and beautiful recipes for every occasion", 1, 0) 
all2$our_dumb_century <- ifelse(all2$`Book-Title` == "our dumb century: the onion presents 100 years of headlines from america's finest news source", 1, 0) 
all2$kitchen_god <- ifelse(all2$`Book-Title` == "the kitchen god's wife", 1, 0) 
all2$the_testament <- ifelse(all2$`Book-Title` == "the testament", 1, 0) 
all2$what_if <- ifelse(all2$`Book-Title` == "what if?: the world's foremost military historians imagine what might have been", 1, 0) 
```

```{r}
all1 <- all2 %>%
  select(`Book-Title`) %>%
  group_by(`Book-Title`) %>%
  summarise(anzahl_buecher = n())
```


```{r}
all3 <- all2[,-1:-2]
```


```{r}
(all.dist <- dist(scale(all3), method="euclidean"))
```

```{r}
all.hc <- hclust(all.dist, method = "complete")
plot(all.hc)
```

```{r}
all.scaled <- as.data.frame(scale(all3))
```

```{r}
wss <- (nrow(all.scaled)-1)*sum(apply(all.scaled,2,var))
  for (i in 2:10) wss[i] <- sum(kmeans(all.scaled,
                                       centers=i)$withinss)
plot(1:10, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")
```
```{r}
k.means.fit <- kmeans(all.scaled, 5)
```
```{r}
clusplot(all3, k.means.fit$cluster, color=TRUE, shade=TRUE,
labels=4, lines=0, main="K-means cluster plot")
```
```{r}
table(all2$`Book-Title`, k.means.fit$cluster)
```

```{r}
clusplot(all3, k.means.fit$cluster, color=TRUE, shade=TRUE,
labels=4, lines=0, main="K-means cluster plot")
```


```{r}
table(all2$Age, k.means.fit$cluster)
```

